project:
  type: website
  render:
  - "*.qmd"
  - "*.md"
  - "!quizzes/"
  - "!exam/"
  - "!assignments/"
  - "!next-time*"
  - "!assignments/assign03/data"
  output-dir: docs
  resources:
  - "assets/*"
  - "data/*"
  - "images/*"
  - "gifs/*"
  - "week*/slides.qmd"
  - "week*/tutorial.qmd"
  - "week*/slides.R"
  - "week*/slides.pdf"
  - "week*/worksheet.qmd"
  - "!assignments/"
website:
  title: "ETC5521: Diving Deeply into Data Exploration"
  site-url: "https://ddde.numbat.space"
  navbar:
    background: "#006dae"
    left:
      - href: index.qmd
        text: Home
        icon: house-fill
      - text: Schedule
        icon: calendar2-fill
        menu:
          - week1/index.qmd
          - week2/index.qmd
          - week3/index.qmd
          - week4/index.qmd
          - week5/index.qmd
          - week6/index.qmd
          - week7/index.qmd
          - week8/index.qmd
          - week9/index.qmd
          - week10/index.qmd
          - week11/index.qmd
          - week12/index.qmd
      - text: Discussion
        icon: chat-fill
        href: "https://edstem.org/au/courses/27016/discussion/"
      - text: Moodle
        icon: mortarboard-fill
        href: "https://learning.monash.edu/course/view.php?id=34784"
      - text: Resources
        icon: book
        href: resources.qmd
    right:
      - icon: github
        href: https://github.com/numbats/ddde

date-format: "D MMMM YYYY"

format:
  html:
    theme: [cosmo, numbat.scss]
    highlight: textmate
    toc: true
    mainfont: "Fira Sans"
    html-math-method: katex
    include-in-header:
      file: header.html


execute:
  echo: false
  warning: false
  message: false
