---
title: "ETC5521 Resources"
---

# Books and articles

- Cook and Swayne (2007) Interactive and Dynamic Graphics for Data Analysis, [Introduction](http://ggobi.org/book/intro.pdf)
- Donoho (2017) [50 Years of Data Science](https://www.tandfonline.com/doi/full/10.1080/10618600.2017.1384734)
- Staniak and Biecek (2019) [The Landscape of R Packages for Automated Exploratory Data Analysis](https://arxiv.org/pdf/1904.02101.pdf)
- Huebner et al (2018) [A Contemporary Conceptual Framework for Initial Data Analysis](https://muse.jhu.edu/article/793379/pdf)
- Huebner et al (2020) [Hidden analyses](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-020-00942-y)
- Chatfield (1985) The Initial Examination of Data. *Journal of the Royal Statistical Society. Series A (General)* **148** <Br>
- Cox & Snell (1981) Applied Statistics. *London: Chapman and Hall.*
- van der Loo and de Jonge (2018). Statistical Data Cleaning with Applications in R. John Wiley and Sons Ltd.
- Hyndman (2014) [Explaining the ABS unemployment fluctuations](https://robjhyndman.com/hyndsight/abs-seasonal-adjustment-2/)
- Buja et al. (2009). [Statistical Inference for Exploratory Data Analysis and Model Diagnostics.](https://royalsocietypublishing.org/doi/10.1098/rsta.2009.0120) Philosophical Transactions. Series A, Mathematical, Physical, and Engineering Sciences 367 (1906): 4361–83.
- Wickham et al (2010) [Graphical Inference for Infovis.](https://doi.org/10.1109/TVCG.2010.161) IEEE Transactions on Visualization and Computer Graphics 16 (6): 973–79.
- Hofmann et al (2012) [Graphical Tests for Power Comparison of Competing Designs.](https://doi.org/10.1109/TVCG.2012.230) IEEE Transactions on Visualization and Computer Graphics 18 (12): 2441–48.
- Majumder et al (2013) [Validation of Visual Statistical Inference, Applied to Linear Models.](https://doi.org/10.1080/01621459.2013.808157) Journal of the American Statistical Association 108 (503): 942–56.
- Josse et al (2022) [R-miss-tastic](https://rmisstastic.netlify.app)

