---
title: "Week 2: Learning from history"
---

```{r}
week <- 2
source(here::here("course_info.R"))
```

## Main reference

```{r}
#| output: asis
schedule |>
  filter(Week == week) |>
  mutate(ref = glue::glue("[{Reference}]({Reference_URL})")) |>
  pull(ref)
```

## What you will learn this week

- The historical origins of EDA
- Pencil and paper methods like stem-and-leaf plots
- How to symmetrise and linearise your data
- Where EDA is relevant today

## Lecture slides

- [html](https://ddde.numbat.space/week2/slides.html)
- [pdf](https://ddde.numbat.space/week2/slides.pdf)
- [qmd](https://ddde.numbat.space/week2/slides.qmd)
- [R](https://ddde.numbat.space/week2/slides.R)

## Worksheet

- [qmd](https://ddde.numbat.space/week2/worksheet.qmd)
- [html](https://ddde.numbat.space/week2/worksheet.html)

## Tutorial instructions

- [html](https://ddde.numbat.space/week2/tutorial.html)
- [qmd](https://ddde.numbat.space/week2/tutorial.qmd)


```{r}
#| output: asis
show_assignments(week)
```
