---
title: "Week 4: Using computational tools to determine whether what is seen in the data can be assumed to apply more broadly"
---

```{r}
week <- 4
source(here::here("course_info.R"))
```

## Main reference

```{r}
#| output: asis
schedule |>
  filter(Week == week) |>
  mutate(ref = glue::glue("[{Reference}]({Reference_URL})")) |>
  pull(ref)
```

## What you will learn this week

- revision of statistical inference
- using re-sampling methods to calibrate reading patterns
- generating lineups of plots
- how to specify the null hypothesis
- calculating $p$-value and power

## Lecture slides

- [html](https://ddde.numbat.space/week4/slides.html)
- [pdf](https://ddde.numbat.space/week4/slides.pdf)
- [qmd](https://ddde.numbat.space/week4/slides.qmd)
- [R](https://ddde.numbat.space/week4/slides.R)

## Worksheet

- [qmd](https://ddde.numbat.space/week4/worksheet.qmd)
- [html](https://ddde.numbat.space/week4/worksheet.html)

## Tutorial instructions

- [html](https://ddde.numbat.space/week4/tutorial.html)
- [qmd](https://ddde.numbat.space/week4/tutorial.qmd)

```{r}
#| output: asis
show_assignments(4)
```
