---
title: "Week 3: Initial data analysis and model diagnostics: Model dependent exploration and how it differs from EDA"
---

```{r}
week <- 3
source(here::here("course_info.R"))
```

## Main reference

```{r}
#| output: asis
schedule |>
  filter(Week == week) |>
  mutate(ref = glue::glue("[{Reference}]({Reference_URL})")) |>
  pull(ref)
```

## What you will learn this week

- Role of IDA
- Techniques for
    - data screening
    - data cleaning
    - imputation
    - validation
- Checking assumptions for hypothesis testing and fitting linear models

## Lecture slides

- [html](https://ddde.numbat.space/week3/slides.html)
- [pdf](https://ddde.numbat.space/week3/slides.pdf)
- [qmd](https://ddde.numbat.space/week3/slides.qmd)
- [R](https://ddde.numbat.space/week3/slides.R)

## Worksheet

- [qmd](https://ddde.numbat.space/week3/worksheet.qmd)
- [html](https://ddde.numbat.space/week3/worksheet.html)

## Tutorial instructions

- [html](https://ddde.numbat.space/week3/tutorial.html)
- [qmd](https://ddde.numbat.space/week3/tutorial.qmd)

## Assignments

```{r}
#| output: asis
show_assignments(week)
```
