---
title: "Week 5: Working with a single variable, making transformations, detecting outliers, using robust statistics"
---

```{r}
week <- 5
source(here::here("course_info.R"))
```

## Main reference

```{r}
#| output: asis
schedule |>
  filter(Week == week) |>
  mutate(ref = glue::glue("[{Reference}]({Reference_URL})")) |>
  pull(ref)
```

## What you will learn this week

- Numeric and visual summaries for a single variable
- Common features to discover
- Tools for inference for a single variable
- Imputing missings on a single variable

## Lecture slides

- [html](https://ddde.numbat.space/week5/slides.html)
- [pdf](https://ddde.numbat.space/week5/slides.pdf)
- [qmd](https://ddde.numbat.space/week5/slides.qmd)
- [R](https://ddde.numbat.space/week5/slides.R)

## Worksheet

- [qmd](https://ddde.numbat.space/week5/worksheet.qmd)
- [html](https://ddde.numbat.space/week5/worksheet.html)

## Tutorial instructions

- [html](https://ddde.numbat.space/week5/tutorial.html)
- [qmd](https://ddde.numbat.space/week5/tutorial.qmd)

```{r}
#| output: asis
show_assignments(5)
```
